# Force 1D
This code can be used to solve statics by FEM in one dimension.

Also work in 1D heat transfer.

The formula is $K'u = F$, and $Ku = P$
where K is equivalent stiffness matrix,
      K' is stiffness matrix with boundry condition,
      u is displacement of nodes,
      F is outer force,
      P is reaction force
      
**Note: The index is started from 0**

## Question and custom data
![](https://raw.githubusercontent.com/linnil1/2019FEM/master/images/Force_1D.png)

There are three parameters.
* `k_equ` is an array defined the equivalent stiffness value between each two nodes.
   The number of points are the length of K plus 1.
* `boundry` is an array, e.g. `[(0, 10),]` means $u_0=10$.
* `F` is an array, e.g. `[(0, 200), (4, 30)]` means $F_0=200$ and $F_4=30$.

In [1]:
import numpy as np

k_equ = [975, 845, 775, 585]
F = [(4, 1)]
boundry = [(0, 0)]

## Prepare big matrix table

In [2]:
# set table
m = np.int(len(k_equ) + 1)
bigT = np.zeros([m, m])
# calculate T
for i, k in enumerate(k_equ):
    bigT[i:i+2, i:i+2] += np.array([[1, -1], [-1, 1]]) * k
print("T")
print(bigT)

T
[[ 975. -975.    0.    0.    0.]
 [-975. 1820. -845.    0.    0.]
 [   0. -845. 1620. -775.    0.]
 [   0.    0. -775. 1360. -585.]
 [   0.    0.    0. -585.  585.]]


## Prepare big matrix with boundry condition

In [3]:
# Set boundary on table
P = np.zeros(m)
boundT = bigT.copy()
for bound in boundry:
    boundT[bound[0], :] = 0
    boundT[bound[0], bound[0]] = 1
    P[bound[0]] = bound[1]
print("boundray Table")
print(boundT)

# set boundry on force
for f in F:
    P[f[0]] = f[1]
print("P")
print(P)

boundray Table
[[ 1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-9.75e+02  1.82e+03 -8.45e+02  0.00e+00  0.00e+00]
 [ 0.00e+00 -8.45e+02  1.62e+03 -7.75e+02  0.00e+00]
 [ 0.00e+00  0.00e+00 -7.75e+02  1.36e+03 -5.85e+02]
 [ 0.00e+00  0.00e+00  0.00e+00 -5.85e+02  5.85e+02]]
P
[0. 0. 0. 0. 1.]


## Solve.

In [4]:
u = np.linalg.inv(boundT).dot(P)
print("u")
print(u)

print("R")
print(bigT.dot(u))

u
[6.83214169e-19 1.02564103e-03 2.20907298e-03 3.49939556e-03
 5.20879727e-03]
R
[-1.  0.  0.  0.  1.]
